### ISSUE TITLE
Retry on JSONDecodeError?

### ISSUE THREAD

**Issue by levi-rs** [travispavek/testrail-python#49]
@travispavek: I run roughly 15,000 tests a week in ~200 runs, and see errors like this about 5 times a week:
```
Traceback (most recent call last):
  File "<path to workspace>/.pyenv/bin/nightmare", line 9, in <module>
    load_entry_point('nightmare==0.0.1', 'console_scripts', 'nightmare')()
  File "<path to workspace>/nightmare/cli.py", line 113, in main
    BehaveController(**vars(args)).run_tests()
  File "<path to workspace>/nightmare/behave_controller.py", line 93, in run_tests
    results.append(self._run_test(test))
  File "<path to workspace>/nightmare/behave_controller.py", line 245, in _run_test
    result.status = self._tr.status(status_str)
  File "<path to workspace>/.pyenv/src/testrail-python/testrail/helper.py", line 16, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kw)
  File "<path to workspace>/.pyenv/src/testrail-python/testrail/helper.py", line 32, in func_wrapper
    items = func(*args)
  File "<path to workspace>/.pyenv/src/testrail-python/testrail/client.py", line 293, in _status_by_name
    return filter(lambda s: s.name == name.lower(), self.statuses())
  File "<path to workspace>/.pyenv/src/testrail-python/testrail/client.py", line 284, in statuses
    return map(Status, self.api.statuses())
  File "<path to workspace>/.pyenv/src/testrail-python/testrail/api.py", line 433, in statuses
    _statuses = self._get('get_statuses')
  File "<path to workspace>/.pyenv/src/testrail-python/testrail/api.py", line 455, in _get
    content = r.json()
  File "<path to workspace>/.pyenv/lib/python3.4/site-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "<path to workspace>/.pyenv/lib/python3.4/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "<path to workspace>/.pyenv/lib/python3.4/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "<path to workspace>/.pyenv/lib/python3.4/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

In short, the response from the TestRail endpoint is not valid JSON, which throws the decode error.

How would you feel about adding a [retry decorator](https://pypi.python.org/pypi/retry) to the `api._get` method that would automatically handle and retry the `_get` call if a JSONDecodeError gets thrown?

```
from json import JSONDecodeError

import retry

# ...

    @retry(JSONDecodeError, tries=3, delay=0.5, backoff=0.5)
    def _get(self, uri, params=None):
        # ...
```

**Comment by levi-rs** [comment]
After doing some digging, it looks like I'm probably getting the 429 status_code response (Too Many Requests)

**Comment by travispavek** [comment]
So I actually thought that I had implemented this but must not have.  When you run into to many requests, testrail will return a wait time in seconds specify when you can try again.  We could easily capture that in the get/post calls and retry after the wait is over.

**Comment by levi-rs** [comment]
Im working on pull request for this now, just need to verify it works.
