### ISSUE TITLE
Ignore cert verification

### ISSUE THREAD

**Issue by harsh-kotak** [travispavek/testrail-python#52]
Can you add an option to ignore Certificate verification? I am getting SSL3_GET_SERVER_CERTIFICATE:certificate verify failed error. Our testrail instance does not have a valid certificate.

**Comment by travispavek** [comment]
You now have two options to disable ssl cert verification.

1. Set environment variable: TESTRAIL_VERIFY_SSL to false
2. In your testrail config add "verify_ssl = 'false'"

Default is True, environment variable will override config file.

I haven't actually tested that this works so please let me know if things look good. So we can close this ticket.

**Comment by harsh-kotak** [comment]
It does not show the certificate error but it broke few other things.

`Traceback (most recent call last):
  File "test.py", line 5, in <module>
    testrail = TestRail(project_id=106)
  File "/usr/local/lib/python2.7/dist-packages/testrail/client.py", line 21, in __init__
    self.api = API(email=email, key=key, url=url)
  File "/usr/local/lib/python2.7/dist-packages/testrail/api.py", line 103, in __init__
    config = self._conf()
  File "/usr/local/lib/python2.7/dist-packages/testrail/api.py", line 117, in _conf
    config = yaml.load(f)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not found expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "/home/hkotak/.testrail.conf", line 5, column 5
could not found expected ':'
  in "/home/hkotak/.testrail.conf", line 6, column 1`

**Comment by travispavek** [comment]
I apologies I meant to say "verify_ssl: 'false'" not '='

**Comment by harsh-kotak** [comment]
That does not fix it. On using ":" it gives the certificate verify failed error.

**Comment by travispavek** [comment]
@harsh-kotak Sorry for the delay but I had to get a local instance installed to repro this.  However my fix seems to be working.  Did you pull the latest master? If you installed using PIP know that this fix is not yet in latest version.

**Comment by travispavek** [comment]
I believe this issue is now fixed. @harsh-kotak if you think otherwise please reopen.

**Comment by harsh-kotak** [comment]
Fixed. Thank you.

**Comment by sleonov** [comment]
I can connect to http URL of my testrail server
When I use https URL I get ssl verification error, even with: export TESTRAIL_VERIFY_SSL=false

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

**Comment by travispavek** [comment]
@sleonov 
Could you try putting "verify_ssl: 'false'" in your .testrail.conf file? Let me know if that works.

**Comment by sleonov** [comment]
If I switch to .testrail.conf then it works with a few warning...but I get results back:

/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)

**Comment by sleonov** [comment]
Do you think it _may_ be worth adding verify_ssl paramter to __init__ function alongside email/key/url  ?

**Comment by travispavek** [comment]
yeah we can.  not sure why the env var isn't working though.  I will need to look into that.
